# -*- coding: utf-8 -*-
"""Robotic_Project_MultiCar_with_Color.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iDhOaiqHo2sXszgeNr6h-dIhwSGlAJj5
"""

!pip install pybullet imageio-ffmpeg matplotlib tqdm pillow

import pybullet as p
import pybullet_data
import time
import math
import numpy as np
import imageio_ffmpeg
from base64 import b64encode
from IPython.display import HTML
from tqdm import trange

# ================= 1. SETUP SIMULAZIONE =================
p.connect(p.DIRECT) # simulazione headless (senza GUI), più veloce e adatta al rendering video
p.resetSimulation()
p.setAdditionalSearchPath(pybullet_data.getDataPath())
p.setGravity(0, 0, -9.81)

R_BASE_X, R_BASE_Y = 35, 25 #raggio base ellisse
TRACK_WIDTH = 12.0 #larghezza pista
N_POINTS = 600 # risoluzione traiettoria

def get_track_point(theta, side=0): #theta = posizione angolare,side = spostamento angolare
    variation = 4.0 * math.sin(3 * theta) + 2.0 * math.cos(5 * theta) #creare curve irregolari
    r_x = R_BASE_X + (side * TRACK_WIDTH / 2) + variation #calcola raggio locale, side sposta verso bordo pista
    r_y = R_BASE_Y + (side * TRACK_WIDTH / 2) + variation #calcola raggio locale, side sposta verso bordo pista
    return np.array([r_x * math.cos(theta), r_y * math.sin(theta)]) #converte coordinate polari

# ================= 2. CARICAMENTO AGENTI =================
ground_id = p.loadURDF("plane.urdf") #crea terreno
p.changeVisualShape(ground_id, -1, rgbaColor=[0.1, 0.5, 0.1, 1]) #cambia colore prato

def load_car(pos, angle, color): #crea auto con colore e posizione specifica
    car_id = p.loadURDF("racecar/racecar.urdf", pos, p.getQuaternionFromEuler([0, 0, angle])) #carica modello auto
    for i in range(-1, p.getNumJoints(car_id)):
        p.changeVisualShape(car_id, i, rgbaColor=color) #cambia colore del modello
    return car_id

# PARTENZA 2x2 PARALLELA (SFALSATA)
# Colonna Sinistra (side=-0.3), Colonna Destra (side=0.3)
# La colonna destra ha un angolo theta minore (più indietro)
# Per creare la griglia delle auto
# FILA 1 (Avanti)
car1 = load_car(get_track_point(0.12, -0.3).tolist() + [0.1], 1.6, [0, 1, 0, 1])    # VERDE (Sinistra)
car2 = load_car(get_track_point(0.10, 0.3).tolist() + [0.1], 1.6, [1, 1, 0, 1])     # GIALLA (Destra - Indietro)

# FILA 2 (Dietro)
car3 = load_car(get_track_point(0.05, -0.3).tolist() + [0.1], 1.6, [1, 0, 0, 1])    # ROSSA (Sinistra)
car4 = load_car(get_track_point(0.03, 0.3).tolist() + [0.1], 1.6, [0, 0, 1, 1])     # BLU (Destra - Indietro)

cars = [car1, car2, car3, car4]

numRays = 15 # Numero di raggi per il lidar
rayLen = 7.0 # Lunghezza dei raggi (7 metri)
rayAngles = np.linspace(-0.8, 0.8, numRays) #distribuiti davanti all'auto simulano il sensore di prossimità

# ================= 3. COSTRUZIONE CIRCUITO =================
def build_race_track(): # Disegna tutta la pista
    angles = np.linspace(0, 2 * np.pi, N_POINTS) # Angoli lungo tutto il circuito
    step = 2
    for i in range(0, len(angles), step): #Costruisce la pista con i segmenti
        a_curr, a_next = angles[i], angles[(i + step) % len(angles)]
        p_s, p_e = get_track_point(a_curr, 0), get_track_point(a_next, 0)
        mid = [(p_s[0] + p_e[0]) / 2, (p_s[1] + p_e[1]) / 2, 0.005]
        angle = math.atan2(p_e[1] - p_s[1], p_e[0] - p_s[0])
        dist = np.linalg.norm(p_e - p_s)

        vis_road = p.createVisualShape(p.GEOM_BOX, halfExtents=[dist/2 + 0.1, TRACK_WIDTH/2 + 0.1, 0.001], rgbaColor=[0.15, 0.15, 0.15, 1]) #ogni segmento è un rettangolo mostra le caratteristiche tra cui il colore, solo visuale, non collisione
        p.createMultiBody(0, -1, vis_road, mid, p.getQuaternionFromEuler([0, 0, angle]))

        kerb_color = [1, 1, 1, 1] if (i // (step*4)) % 2 == 0 else [1, 0, 0, 1] # Creazione cordoli alternati in rossi e bianchi come f1
        for side in [-1, 1]:  #lato destro e sinistro
            p_s_k, p_e_k = get_track_point(a_curr, side * 1.01), get_track_point(a_next, side * 1.01)
            mid_k = [(p_s_k[0] + p_e_k[0]) / 2, (p_s_k[1] + p_e_k[1]) / 2, 0.01]
            vis_kerb = p.createVisualShape(p.GEOM_BOX, halfExtents=[dist/2 + 0.1, 0.5, 0.002], rgbaColor=kerb_color)
            p.createMultiBody(0, -1, vis_kerb, mid_k, p.getQuaternionFromEuler([0, 0, angle]))

    # Linea di partenza
    start_angle = 0.22
    p_start = get_track_point(start_angle, 0)
    p_prev = get_track_point(start_angle - 0.01, 0)
    road_angle = math.atan2(p_start[1] - p_prev[1], p_start[0] - p_prev[0])

    rows, cols = 2, 12
    square_size = TRACK_WIDTH / cols
    for r in range(rows):
        for c in range(cols):
            color = [1, 1, 1, 1] if (r + c) % 2 == 0 else [0, 0, 0, 1]
            side_pos = -1.0 + (c * 2.0 / (cols-1))
            pos = get_track_point(start_angle + (r * 0.005), side_pos)
            vis_sq = p.createVisualShape(p.GEOM_BOX, halfExtents=[0.2, square_size/2, 0.003], rgbaColor=color)
            p.createMultiBody(0, -1, vis_sq, [pos[0], pos[1], 0.02], p.getQuaternionFromEuler([0, 0, road_angle]))

    # Muri esterni
    for i in range(0, len(angles), 6):
        a_curr, a_next = angles[i], angles[(i + 6) % len(angles)]
        for side in [-1.2, 1.2]:
            p_s, p_e = get_track_point(a_curr, side), get_track_point(a_next, side)
            mid = [(p_s[0] + p_e[0]) / 2, (p_s[1] + p_e[1]) / 2, 0.25]
            angle = math.atan2(p_e[1] - p_s[1], p_e[0] - p_s[0])
            dist = np.linalg.norm(p_e - p_s)
            col = p.createCollisionShape(p.GEOM_BOX, halfExtents=[dist/2, 0.1, 0.25]) # Collisione
            vis = p.createVisualShape(p.GEOM_BOX, halfExtents=[dist/2, 0.1, 0.25], rgbaColor=[0.9, 0.9, 0.9, 1])
            p.createMultiBody(0, col, vis, mid, p.getQuaternionFromEuler([0, 0, angle]))

    for _ in range(30):
        ra = np.random.uniform(0.6, 2 * np.pi - 0.6) # random.uniform restituisce un numero casuale fra a e b,ra è un punto della pista in cui piazzare l'oggetto, compreso fra 0.6 e 2 pigreco perchè evita di piazzare i cubi vicino alla linea di partenza,evita che i cubi compaiono sulla griglia iniziale e previene collisioni all'avvio
        rs = np.random.uniform(-0.4, 0.4) # oggetto spostato lateralmente rispetto al centro pista
        cube_id = p.loadURDF("cube.urdf", get_track_point(ra, rs).tolist() + [0.2], globalScaling=0.5) # Ostacoli casuali
        p.changeVisualShape(cube_id, -1, rgbaColor=[1, 0.5, 0, 1])

build_race_track()

# ================= 4. LOGICA DI GUIDA =================
def get_lidar_avoidance(car_id): # Calcola la correzione dello sterzo
    pos, orn = p.getBasePositionAndOrientation(car_id)
    matrix = p.getMatrixFromQuaternion(orn)
    forward, side_vec = np.array([matrix[0], matrix[3], matrix[6]]), np.array([matrix[1], matrix[4], matrix[7]])
    rays_to = [np.array(pos) + (forward * math.cos(ang) + side_vec * math.sin(ang)) * rayLen for ang in rayAngles]
    results = p.rayTestBatch([pos] * numRays, rays_to) #lancia tutti i raggi insieme
    steering_adj = 0
    for i, res in enumerate(results):
        if res[2] < 1.0: steering_adj -= rayAngles[i] * (1.0 - res[2]) * 0.7 #calcola se un oggetto è vicino, più l'oggetto è vicino, più sterza in direzione opposta all'ostacolo
    return steering_adj

path_pts = np.array([get_track_point(a, 0) for a in np.linspace(0, 2*np.pi, N_POINTS)])
video = imageio_ffmpeg.write_frames('staggered_start.mp4', (480, 368), fps=30)
video.send(None)

for t in trange(33500): # 1100 secondi a 30 fps
    for car in cars:
        pos, orn = p.getBasePositionAndOrientation(car) # stato attuale
        dists = np.sum((path_pts - np.array(pos[:2]))**2, axis=1) # distanza da ogni punto pista

        # Look-ahead dinamico per stabilità in gruppo
        look_ahead = 18 if car in [car2, car4] else 14
        target_idx = (np.argmin(dists) + look_ahead) % N_POINTS # punto davanti, look-ahead controller

        yaw = p.getEulerFromQuaternion(orn)[2]
        angle_to_target = math.atan2(path_pts[target_idx][1]-pos[1], path_pts[target_idx][0]-pos[0]) - yaw
        angle_to_target = (angle_to_target + math.pi) % (2 * math.pi) - math.pi

        avoidance = get_lidar_avoidance(car) # correzione sensori
        final_steer = np.clip(angle_to_target + avoidance * 2.8, -0.6, 0.6)

        # Velocità differenziata
        if car == car2: current_vel = 31.0   # Gialla: la più veloce
        elif car == car3: current_vel = 30.5 # Rossa: velocità media
        else: current_vel = 30.0             # Verde e Blu: le più lente

        for w in [2, 3, 5, 7]:
            p.setJointMotorControl2(car, w, p.VELOCITY_CONTROL, targetVelocity=current_vel, force=70) # motore route
        for s in [4, 6]:
            p.setJointMotorControl2(car, s, p.POSITION_CONTROL, targetPosition=final_steer) # sterzo ruote anteriori

    p.stepSimulation()
    if t % 20 == 0:
        # Inquadratura dall'alto che segue il gruppo
        avg_pos = np.mean([p.getBasePositionAndOrientation(c)[0] for c in cars], axis=0)
        view_mat = p.computeViewMatrixFromYawPitchRoll(cameraTargetPosition=avg_pos, distance=15, yaw=0, pitch=-89, roll=0, upAxisIndex=2)
        img = p.getCameraImage(480, 368, view_mat, p.computeProjectionMatrixFOV(60, 480/368, 0.1, 250))[2][:,:,:3] # p.getCameraImage vista dall'alto + registrazione MP4
        video.send(np.ascontiguousarray(img))

video.close() # salva video
p.disconnect() # chiudi simulazione
mp4 = open('staggered_start.mp4', 'rb').read()
HTML(f'<video width=480 controls><source src="data:video/mp4;base64,{b64encode(mp4).decode()}" type="video/mp4"></video>')