# -*- coding: utf-8 -*-
"""Robotic-Project_SingleCar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SXcJlWd2SVhINjJ7gRKst5DITSGVrqiT
"""

!pip install pybullet imageio-ffmpeg matplotlib tqdm pillow

import pybullet as p
import pybullet_data
import time
import math
import numpy as np
import imageio_ffmpeg
from base64 import b64encode
from IPython.display import HTML
from tqdm import trange

# ================= 1. SETUP =================
p.connect(p.DIRECT)  # simulazione headless (senza GUI), più veloce e adatta al rendering video
p.resetSimulation() # pulitura simulazioni precedenti
p.setAdditionalSearchPath(pybullet_data.getDataPath()) # per ottnere informazioni su plane.urdf e racecar.urdf
p.setGravity(0, 0, -9.81) # impostazione della gravità per rendere il tutto reale

filename = 'fpv_circuit.mp4'
R_BASE_X, R_BASE_Y = 15, 12 #raggio base ellisse
TRACK_WIDTH = 5.0 #larghezza pista
N_POINTS = 500 # risoluzione traiettoria (più alto => più preciso)

def get_track_point(theta, side=0): #theta = posizione angolare,side = spostamento angolare
    variation = 1.5 * math.sin(3 * theta) + 1.0 * math.cos(5 * theta) #creare curve irregolari
    r_x = R_BASE_X + (side * TRACK_WIDTH / 2) + variation #calcola raggio locale, side sposta verso bordo pista
    r_y = R_BASE_Y + (side * TRACK_WIDTH / 2) + variation #calcola raggio locale, side sposta verso bordo pista
    return np.array([r_x * math.cos(theta), r_y * math.sin(theta)]) #converte coordinate polari

# ================= 2. AGENTE E TERRENO =================
ground_id = p.loadURDF("plane.urdf") # crea terreno
p.changeVisualShape(ground_id, -1, rgbaColor=[0.1, 0.5, 0.1, 1])  #cambia colore prato

car_pos = get_track_point(0, 0).tolist() + [0.1]
car_id = p.loadURDF("racecar/racecar.urdf", car_pos, p.getQuaternionFromEuler([0, 0, 1.5])) # sterzo sulle ruote anteriori, orientato correttamente all'avvio
for i in range(-1, p.getNumJoints(car_id)):
    p.changeVisualShape(car_id, i, rgbaColor=[0, 0, 1, 1]) #cambia colore del modello

numRays = 15 # Numero di raggi per il lidar
rayLen = 5.0 # Lunghezza dei raggi (5 metri)
rayAngles = np.linspace(-0.7, 0.7, numRays) #distribuiti davanti all'auto simulano il sensore di prossimità

# ================= 3. COSTRUZIONE SCENA =================
def build_scene(): # Disegna tutta la pista
    angles = np.linspace(0, 2 * np.pi, N_POINTS) ## Angoli lungo tutto il circuito
    cross_angles = [np.pi/2, 3*np.pi/2]
    lights = []

    for i in range(0, len(angles), 2): #Costruisce la pista con i segmenti
        a_curr, a_next = angles[i], angles[(i + 2) % len(angles)]
        p_s, p_e = get_track_point(a_curr, 0), get_track_point(a_next, 0)
        mid = [(p_s[0] + p_e[0]) / 2, (p_s[1] + p_e[1]) / 2, 0.01]
        angle = math.atan2(p_e[1] - p_s[1], p_e[0] - p_s[0])
        dist = np.linalg.norm(p_e - p_s)

        vis_road = p.createVisualShape(p.GEOM_BOX, halfExtents=[dist/2 + 0.1, TRACK_WIDTH/2, 0.001], rgbaColor=[0.15, 0.15, 0.15, 1]) #ogni segmento è un rettangolo mostra le caratteristiche tra cui il colore, solo visuale, non collisione
        p.createMultiBody(0, -1, vis_road, mid, p.getQuaternionFromEuler([0, 0, angle]))

        if any(abs(a_curr - ca) < 0.12 for ca in cross_angles): # attraversamento pedonale
            for stripe in np.linspace(-0.6, 0.6, 5):
                stripe_pos = get_track_point(a_curr, stripe)
                vis_stripe = p.createVisualShape(p.GEOM_BOX, halfExtents=[0.4, 0.15, 0.002], rgbaColor=[1, 1, 1, 1])
                p.createMultiBody(0, -1, vis_stripe, [stripe_pos[0], stripe_pos[1], 0.02], p.getQuaternionFromEuler([0, 0, angle]))

    for ca in cross_angles: #semaforo
        sem_pos = get_track_point(ca, 1.5).tolist()
        p.createMultiBody(0, -1, p.createVisualShape(p.GEOM_CYLINDER, radius=0.1, length=3, rgbaColor=[0.2, 0.2, 0.2, 1]), [sem_pos[0], sem_pos[1], 1.5])
        l_id = p.createMultiBody(0, -1, p.createVisualShape(p.GEOM_SPHERE, radius=0.4), [sem_pos[0], sem_pos[1], 3.2])
        lights.append(l_id)

    for _ in range(8): # ostacoli
        ra = np.random.uniform(0, 2*np.pi)
        if all(abs(ra - ca) > 0.4 for ca in cross_angles):
            cube_id = p.loadURDF("cube.urdf", get_track_point(ra, np.random.uniform(-0.15, 0.15)).tolist() + [0.2], globalScaling=0.4)
            p.changeVisualShape(cube_id, -1, rgbaColor=[0.6, 0.3, 0, 1])

    return lights, cross_angles

light_ids, CROSS_ANGS = build_scene()

# ================= 4. LOGICA DI GUIDA E VIDEO =================
path_pts = np.array([get_track_point(a, 0) for a in np.linspace(0, 2*np.pi, N_POINTS)]) # linea ideale centrale
video = imageio_ffmpeg.write_frames(filename, (480, 368), fps=30)
video.send(None)

for t in trange(33000): # 1100 secondi a 30 fps
    is_red = (t % 2000) > 1000 #1000 step verde / 1000 step rosso
    for l_id in light_ids:
        p.changeVisualShape(l_id, -1, rgbaColor=[1, 0, 0, 1] if is_red else [0, 1, 0, 1])

    pos, orn = p.getBasePositionAndOrientation(car_id)
    car_angle = math.atan2(pos[1], pos[0]) # conversione posizione, parametro angolare, usato per capire quanto manca al semaforo
    if car_angle < 0: car_angle += 2 * math.pi

    dists = np.sum((path_pts - np.array(pos[:2]))**2, axis=1)
    nearest_idx = np.argmin(dists) # punto di look ahead,evita oscillazioni, stabilizza traiettoria
    target_idx = (nearest_idx + 14) % N_POINTS

    yaw = p.getEulerFromQuaternion(orn)[2]
    angle_to_center = math.atan2(path_pts[target_idx][1]-pos[1], path_pts[target_idx][0]-pos[0]) - yaw # errore angolare
    angle_to_center = (angle_to_center + math.pi) % (2 * math.pi) - math.pi

    dist_val = np.sqrt(dists[nearest_idx])
    lane_keep = angle_to_center * (1.2 + dist_val * 3.0) # controllo non lineare, più sei fuori dal centro più corregge

    matrix = p.getMatrixFromQuaternion(orn)
    fwd, side = np.array([matrix[0], matrix[3], matrix[6]]), np.array([matrix[1], matrix[4], matrix[7]])
    avoidance = 0
    rays = p.rayTestBatch([pos]*numRays, [np.array(pos)+(fwd*math.cos(a)+side*math.sin(a))*rayLen for a in rayAngles]) #rayTestBatch(...) ogni raggio restituisce distanza e ID oggetto colpito
    for i, res in enumerate(rays):
        if res[2] < 1.0: avoidance -= rayAngles[i] * (1.0 - res[2]) * 2.8 # avoidance ostacolo vicino, sterzo opposto, più vicino più fortee

    final_steer = np.clip(lane_keep + avoidance, -0.6, 0.6) # beahviour based control, emergent behaviour

    # LOGICA SEMAFORO: Stop prima della linea
    target_v = 18
    for ca in CROSS_ANGS:
        dist_to_light = (ca - car_angle + math.pi) % (2*math.pi) - math.pi
        # Modificato l'intervallo: si ferma tra 0.1 e 0.35. Sotto 0.1 "tira dritto"
        if is_red and (0.1 < dist_to_light < 0.35): # se target_v = 0 l'auto si ferma prima, non inchioda al semaforo
            target_v = 0

    for w in [2, 3, 5, 7]: p.setJointMotorControl2(car_id, w, p.VELOCITY_CONTROL, targetVelocity=target_v, force=40) # ruote posteriori velocità
    for s in [4, 6]: p.setJointMotorControl2(car_id, s, p.POSITION_CONTROL, targetPosition=final_steer) # ruote anteriori angolo di sterzo

    p.stepSimulation()

    if t % 20 == 0:
        rot_matrix = p.getMatrixFromQuaternion(orn) # orn orientamento dell'auto, le rotazioni non si presentano con angoli ma con quaternioni; rotmatrix converte il quaternione in matrice di rotazione, il riusltato non è una matrice ma lista piatta di 9 valori
        forward_vec = [rot_matrix[0], rot_matrix[3], rot_matrix[6]] # estraggo la prima colonna della amtrice di rotazione, La prima colonna della matrice di rotazione rappresenta l’asse X locale del robot nel mondo
        #forward_vec è il vettore direzione “in avanti” del veicolo nel mondo
        # CAMERA: Spostata INDIETRO (-0.5) per vedere il muso
        camera_pos = [
            pos[0] - forward_vec[0] * 0.5,
            pos[1] - forward_vec[1] * 0.5,
            pos[2] + 0.6 # Alzata per una visuale migliore del muso
        ]

        target_pos = [
            pos[0] + forward_vec[0] * 3.0,
            pos[1] + forward_vec[1] * 3.0,
            pos[2] + 0.2
        ]

        view_mat = p.computeViewMatrix(cameraEyePosition=camera_pos, cameraTargetPosition=target_pos, cameraUpVector=[0, 0, 1])
        proj_mat = p.computeProjectionMatrixFOV(fov=85, aspect=480/368, nearVal=0.1, farVal=100)
        img = p.getCameraImage(480, 368, view_mat, proj_mat)[2][:,:,:3]
        video.send(np.ascontiguousarray(img))

        #if t % 20 == 0:
        # Visuale dall'alto centrata sulla posizione corrente dell'auto
        #view_mat = p.computeViewMatrixFromYawPitchRoll(
        #    cameraTargetPosition=pos, # Segue l'auto
        #    distance=12,              # Altezza della telecamera
        #    yaw=0,                    # Rotazione orizzontale
        #    pitch=-85,                # Inclinazione (quasi perpendicolare al suolo)
        #    roll=0,
        #    upAxisIndex=2
        #)

        # Proiezione standard per visuale dall'alto
        #proj_mat = p.computeProjectionMatrixFOV(fov=60, aspect=480/368, nearVal=0.1, farVal=100)

        #img = p.getCameraImage(480, 368, view_mat, proj_mat)[2][:,:,:3]
        #video.send(np.ascontiguousarray(img))

video.close()
p.disconnect()
mp4 = open(filename, 'rb').read()
HTML(f'<video width=480 controls><source src="data:video/mp4;base64,{b64encode(mp4).decode()}" type="video/mp4"></video>')